#!/usr/bin/env Rscript

# ============================================================
# 13_supplementary_genomic_distribution_figure.R
#
# Create the supplementary figure showing:
# A) genomic distribution of the 57 persistent aa-associated
#    genes and the ANS reference position
# B) zoomed views of ctg004200, ctg005830 and ctg000670,
#    including all annotated genes in the displayed windows
# C) lookup table linking plot numbers to gene IDs and contigs
#
# Expected input generated by scripts 11 and 12:
#   strict_aa_signature_57_genes_annotated_positions.rds
#   gff_genes.rds
#   contig_lengths.rds
#   ANS_genomic_position.csv
#
# By default, <project> is /vol/data/digitalis_rnaseq.
# ============================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(grid)
})


# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

project_dir <- Sys.getenv(
  "DIGITALIS_RNASEQ_DIR",
  unset = "/vol/data/digitalis_rnaseq"
)

results_dir <- file.path(
  project_dir,
  "deseq2",
  "results"
)

outdir <- file.path(
  results_dir,
  "genotype_background_analysis"
)

figdir <- file.path(
  outdir,
  "figures"
)

dir.create(
  figdir,
  recursive = TRUE,
  showWarnings = FALSE
)

strict_file <- file.path(
  outdir,
  "strict_aa_signature_57_genes_annotated_positions.rds"
)

gff_genes_file <- file.path(
  outdir,
  "gff_genes.rds"
)

contig_lengths_file <- file.path(
  outdir,
  "contig_lengths.rds"
)

ans_position_file <- file.path(
  outdir,
  "ANS_genomic_position.csv"
)

for (f in c(
  strict_file,
  gff_genes_file,
  contig_lengths_file,
  ans_position_file
)) {
  if (!file.exists(f)) {
    stop("Missing input file: ", f)
  }
}


# ------------------------------------------------------------
# 2. Load data
# ------------------------------------------------------------

strict_aa_final <- readRDS(
  strict_file
)

gff_genes <- readRDS(
  gff_genes_file
)

contig_lengths <- readRDS(
  contig_lengths_file
)

ans_position <- read.csv(
  ans_position_file,
  stringsAsFactors = FALSE
)


# ------------------------------------------------------------
# 3. General settings
# ------------------------------------------------------------

accent_col <- "#1F6F8B"
highlight_fill <- "#EAF4F8"
line_col <- "grey70"
all_gene_col <- "grey82"
connector_col <- "grey60"
ans_col <- "black"

cluster_contigs <- c(
  "ctg004200",
  "ctg005830",
  "ctg000670"
)

row_spacing <- 1.70


# ------------------------------------------------------------
# 4. Candidate positions and classes
# ------------------------------------------------------------

required_columns <- c(
  "table_no",
  "table_no_fmt",
  "gene_id",
  "seqid",
  "start",
  "end",
  "shrink_rank"
)

if (!all(required_columns %in% names(strict_aa_final))) {
  stop(
    "The stringent candidate table is missing one or more required columns: ",
    paste(
      setdiff(
        required_columns,
        names(strict_aa_final)
      ),
      collapse = ", "
    )
  )
}

candidate_positions <- strict_aa_final[
  ,
  required_columns
]

candidate_positions <- candidate_positions[
  !is.na(candidate_positions$seqid) &
    !is.na(candidate_positions$start) &
    !is.na(candidate_positions$end),
]

candidate_positions$midpoint <- (
  candidate_positions$start +
    candidate_positions$end
) / 2

candidate_positions$gene_class <- ifelse(
  candidate_positions$shrink_rank <= 10,
  "Top-10 gene",
  "Persistent aa-associated gene"
)

candidate_positions$gene_class <- factor(
  candidate_positions$gene_class,
  levels = c(
    "Persistent aa-associated gene",
    "Top-10 gene"
  )
)

candidate_positions$in_zoom <-
  candidate_positions$seqid %in%
  cluster_contigs


# ------------------------------------------------------------
# 5. ANS midpoint
# ------------------------------------------------------------

if (nrow(ans_position) == 0) {
  stop("ANS position table is empty.")
}

ans_position$midpoint <- (
  ans_position$start +
    ans_position$end
) / 2


# ------------------------------------------------------------
# 6. Overview contigs
# ------------------------------------------------------------

candidate_contigs <- unique(
  c(
    candidate_positions$seqid,
    ans_position$seqid
  )
)

overview_contigs <- contig_lengths[
  contig_lengths$seqid %in%
    candidate_contigs,
]

overview_contigs$contig_number <- as.numeric(
  sub(
    "^ctg",
    "",
    overview_contigs$seqid
  )
)

overview_contigs <- overview_contigs[
  order(
    overview_contigs$contig_number
  ),
]


# ------------------------------------------------------------
# 7. Contig order and y positions
# ------------------------------------------------------------

contig_order <- rev(
  overview_contigs$seqid
)

y_breaks <- seq_along(
  contig_order
) * row_spacing

overview_contigs$ypos <- match(
  overview_contigs$seqid,
  contig_order
) * row_spacing

candidate_positions$ypos <- match(
  candidate_positions$seqid,
  contig_order
) * row_spacing

ans_position$ypos <- match(
  ans_position$seqid,
  contig_order
) * row_spacing


# ------------------------------------------------------------
# 8. Highlight contigs enlarged in Panel B
# ------------------------------------------------------------

highlight_df <- data.frame(
  seqid = cluster_contigs,
  ypos = match(
    cluster_contigs,
    contig_order
  ) * row_spacing
)

highlight_df <- highlight_df[
  !is.na(highlight_df$ypos),
]


# ------------------------------------------------------------
# 9. Prepare Panel A labels
# ------------------------------------------------------------

labels_A <- candidate_positions[
  !candidate_positions$in_zoom,
]

labels_A <- labels_A[
  order(
    labels_A$seqid,
    labels_A$midpoint
  ),
]


spread_overview_labels <- function(x) {

  x <- x[
    order(
      x$midpoint
    ),
  ]

  x$point_x <- x$midpoint / 1e6
  x$label_x <- x$point_x
  x$label_y <- unique(x$ypos) + 0.58

  if (nrow(x) == 1) {
    return(x)
  }

  min_sep <- 0.18

  group_id <- c(
    1,
    cumsum(
      diff(x$point_x) >= min_sep
    ) + 1
  )

  groups <- unique(
    group_id
  )

  for (g in groups) {

    idx <- which(
      group_id == g
    )

    if (length(idx) == 1) {
      next
    }

    center <- mean(
      x$point_x[idx]
    )

    new_positions <- center +
      (
        seq_along(idx) -
          (length(idx) + 1) / 2
      ) * min_sep

    if (min(new_positions) < 0.05) {

      new_positions <- new_positions +
        (
          0.05 -
            min(new_positions)
        )
    }

    x$label_x[idx] <- new_positions
  }

  x
}


labels_A <- do.call(
  rbind,
  lapply(
    split(
      labels_A,
      labels_A$seqid
    ),
    spread_overview_labels
  )
)

rownames(labels_A) <- NULL


# ============================================================
# PANEL A
# ============================================================

p_overview <- ggplot() +

  geom_rect(
    data = highlight_df,
    aes(
      xmin = -Inf,
      xmax = Inf,
      ymin = ypos - row_spacing * 0.42,
      ymax = ypos + row_spacing * 0.42
    ),
    inherit.aes = FALSE,
    fill = highlight_fill,
    color = NA
  ) +

  geom_segment(
    data = overview_contigs,
    aes(
      x = 0,
      xend = end / 1e6,
      y = ypos,
      yend = ypos
    ),
    linewidth = 0.45,
    color = line_col
  ) +

  geom_point(
    data = candidate_positions[
      candidate_positions$gene_class ==
        "Persistent aa-associated gene",
    ],
    aes(
      x = midpoint / 1e6,
      y = ypos,
      shape = gene_class
    ),
    size = 2.7,
    color = accent_col
  ) +

  geom_point(
    data = candidate_positions[
      candidate_positions$gene_class ==
        "Top-10 gene",
    ],
    aes(
      x = midpoint / 1e6,
      y = ypos,
      shape = gene_class
    ),
    size = 3.2,
    color = accent_col
  ) +

  geom_segment(
    data = labels_A,
    aes(
      x = point_x,
      xend = label_x,
      y = ypos + 0.08,
      yend = label_y - 0.08
    ),
    linewidth = 0.25,
    color = connector_col
  ) +

  geom_label(
    data = labels_A,
    aes(
      x = label_x,
      y = label_y,
      label = table_no_fmt
    ),
    size = 2.45,
    color = "black",
    fontface = "bold",
    fill = "white",
    linewidth = 0,
    label.padding = unit(
      0.04,
      "lines"
    ),
    vjust = 0
  ) +

  geom_point(
    data = ans_position,
    aes(
      x = midpoint / 1e6,
      y = ypos
    ),
    shape = 8,
    size = 4.2,
    color = ans_col,
    stroke = 1
  ) +

  geom_segment(
    data = ans_position,
    aes(
      x = midpoint / 1e6,
      xend = midpoint / 1e6,
      y = ypos + 0.10,
      yend = ypos + 0.50
    ),
    linewidth = 0.25,
    color = connector_col
  ) +

  geom_label(
    data = ans_position,
    aes(
      x = midpoint / 1e6,
      y = ypos + 0.60,
      label = "ANS"
    ),
    size = 2.7,
    color = "black",
    fontface = "bold",
    fill = "white",
    linewidth = 0,
    label.padding = unit(
      0.04,
      "lines"
    ),
    vjust = 0
  ) +

  scale_shape_manual(
    values = c(
      "Persistent aa-associated gene" = 16,
      "Top-10 gene" = 17
    ),
    name = NULL
  ) +

  scale_y_continuous(
    breaks = y_breaks,
    labels = contig_order,
    expand = expansion(
      mult = c(
        0.01,
        0.06
      )
    )
  ) +

  labs(
    title =
      "A  Genomic distribution of persistent aa-associated genes",
    x = "Position on contig (Mb)",
    y = NULL
  ) +

  coord_cartesian(
    clip = "off"
  ) +

  theme_classic(
    base_size = 11
  ) +

  theme(
    plot.title = element_text(
      face = "bold",
      size = 13,
      hjust = 0
    ),
    axis.text.x = element_text(
      size = 9
    ),
    axis.text.y = element_text(
      size = 8.5
    ),
    axis.ticks.y = element_blank(),
    legend.position = "bottom",
    legend.text = element_text(
      size = 9
    ),
    legend.background = element_rect(
      fill = "white",
      color = NA
    ),
    legend.key = element_rect(
      fill = "white",
      color = NA
    ),
    panel.background = element_rect(
      fill = "white",
      color = NA
    ),
    plot.background = element_rect(
      fill = "white",
      color = NA
    ),
    plot.margin = margin(
      10,
      10,
      5,
      8
    )
  )


# ------------------------------------------------------------
# 10. Prepare Panel B
# ------------------------------------------------------------

all_cluster_genes <- gff_genes[
  gff_genes$seqid %in%
    cluster_contigs,
  c(
    "gene_id",
    "seqid",
    "start",
    "end"
  )
]

all_cluster_genes$midpoint <- (
  all_cluster_genes$start +
    all_cluster_genes$end
) / 2

cluster_candidates <- candidate_positions[
  candidate_positions$seqid %in%
    cluster_contigs,
]


# ------------------------------------------------------------
# 11. Zoom windows
# ------------------------------------------------------------

zoom_windows <- do.call(
  rbind,
  lapply(
    cluster_contigs,
    function(ctg) {

      x <- cluster_candidates[
        cluster_candidates$seqid == ctg,
      ]

      if (nrow(x) == 0) {
        return(NULL)
      }

      xmin0 <- min(
        x$start
      )

      xmax0 <- max(
        x$end
      )

      span <- xmax0 - xmin0

      buffer <- max(
        15000,
        span * 0.12
      )

      data.frame(
        seqid = ctg,
        xmin = max(
          0,
          xmin0 - buffer
        ),
        xmax = xmax0 + buffer
      )
    }
  )
)


# ------------------------------------------------------------
# 12. All annotated genes within zoom windows
# ------------------------------------------------------------

all_cluster_genes_window <- do.call(
  rbind,
  lapply(
    as.character(
      zoom_windows$seqid
    ),
    function(ctg) {

      g <- all_cluster_genes[
        all_cluster_genes$seqid == ctg,
      ]

      w <- zoom_windows[
        zoom_windows$seqid == ctg,
      ]

      g[
        g$midpoint >= w$xmin &
          g$midpoint <= w$xmax,
      ]
    }
  )
)


# ------------------------------------------------------------
# 13. Spread labels in Panel B
# ------------------------------------------------------------

spread_zoom_labels <- function(
  x,
  window_row
) {

  x <- x[
    order(
      x$midpoint
    ),
  ]

  x$point_x <- x$midpoint / 1e6
  x$label_x <- x$point_x
  x$label_y <- 0.052

  xmin_mb <- window_row$xmin / 1e6
  xmax_mb <- window_row$xmax / 1e6
  panel_span <- xmax_mb - xmin_mb

  min_sep <- min(
    0.035,
    max(
      0.022,
      panel_span * 0.055
    )
  )

  margin_x <- max(
    0.010,
    panel_span * 0.025
  )

  left_bound <- xmin_mb + margin_x
  right_bound <- xmax_mb - margin_x

  if (nrow(x) > 1) {

    for (i in 2:nrow(x)) {

      if (
        x$label_x[i] -
          x$label_x[i - 1] <
          min_sep
      ) {

        x$label_x[i] <-
          x$label_x[i - 1] +
          min_sep
      }
    }
  }

  if (
    max(x$label_x) >
      right_bound
  ) {

    shift_left <- max(
      x$label_x
    ) - right_bound

    x$label_x <- x$label_x -
      shift_left
  }

  if (nrow(x) > 1) {

    for (
      i in seq(
        from = nrow(x) - 1,
        to = 1,
        by = -1
      )
    ) {

      if (
        x$label_x[i + 1] -
          x$label_x[i] <
          min_sep
      ) {

        x$label_x[i] <-
          x$label_x[i + 1] -
          min_sep
      }
    }
  }

  if (
    min(x$label_x) <
      left_bound
  ) {

    shift_right <- left_bound -
      min(x$label_x)

    x$label_x <- x$label_x +
      shift_right
  }

  x
}


cluster_candidates <- do.call(
  rbind,
  lapply(
    as.character(
      zoom_windows$seqid
    ),
    function(ctg) {

      x <- cluster_candidates[
        cluster_candidates$seqid == ctg,
      ]

      w <- zoom_windows[
        zoom_windows$seqid == ctg,
      ]

      spread_zoom_labels(
        x,
        w
      )
    }
  )
)


# ------------------------------------------------------------
# 14. Factor order for Panel B
# ------------------------------------------------------------

zoom_levels <- cluster_contigs[
  cluster_contigs %in%
    as.character(
      zoom_windows$seqid
    )
]

cluster_candidates$seqid <- factor(
  cluster_candidates$seqid,
  levels = zoom_levels
)

all_cluster_genes_window$seqid <- factor(
  all_cluster_genes_window$seqid,
  levels = zoom_levels
)

zoom_windows$seqid <- factor(
  zoom_windows$seqid,
  levels = zoom_levels
)


# ============================================================
# PANEL B
# ============================================================

p_zoom <- ggplot() +

  geom_rect(
    data = zoom_windows,
    aes(
      xmin = -Inf,
      xmax = Inf,
      ymin = -Inf,
      ymax = Inf
    ),
    inherit.aes = FALSE,
    fill = highlight_fill,
    color = NA
  ) +

  geom_segment(
    data = zoom_windows,
    aes(
      x = xmin / 1e6,
      xend = xmax / 1e6,
      y = 0,
      yend = 0
    ),
    linewidth = 0.55,
    color = line_col
  ) +

  geom_segment(
    data = all_cluster_genes_window,
    aes(
      x = midpoint / 1e6,
      xend = midpoint / 1e6,
      y = -0.010,
      yend = 0.010
    ),
    linewidth = 0.35,
    color = all_gene_col
  ) +

  geom_segment(
    data = cluster_candidates,
    aes(
      x = point_x,
      xend = label_x,
      y = 0.010,
      yend = 0.045
    ),
    linewidth = 0.35,
    color = connector_col
  ) +

  geom_point(
    data = cluster_candidates[
      cluster_candidates$gene_class ==
        "Persistent aa-associated gene",
    ],
    aes(
      x = point_x,
      y = 0,
      shape = gene_class
    ),
    size = 3.0,
    color = accent_col
  ) +

  geom_point(
    data = cluster_candidates[
      cluster_candidates$gene_class ==
        "Top-10 gene",
    ],
    aes(
      x = point_x,
      y = 0,
      shape = gene_class
    ),
    size = 3.5,
    color = accent_col
  ) +

  geom_label(
    data = cluster_candidates,
    aes(
      x = label_x,
      y = label_y,
      label = table_no_fmt
    ),
    size = 2.7,
    color = "black",
    fontface = "bold",
    fill = "white",
    linewidth = 0,
    label.padding = unit(
      0.05,
      "lines"
    ),
    vjust = 0
  ) +

  scale_shape_manual(
    values = c(
      "Persistent aa-associated gene" = 16,
      "Top-10 gene" = 17
    ),
    name = NULL
  ) +

  facet_wrap(
    ~ seqid,
    nrow = 1,
    scales = "free_x"
  ) +

  scale_y_continuous(
    breaks = NULL,
    limits = c(
      -0.02,
      0.085
    )
  ) +

  labs(
    title =
      "B  Zoom on local groups of persistent aa-associated genes",
    x = "Position on contig (Mb)",
    y = NULL
  ) +

  coord_cartesian(
    clip = "off"
  ) +

  theme_classic(
    base_size = 11
  ) +

  theme(
    plot.title = element_text(
      face = "bold",
      size = 13,
      hjust = 0
    ),
    axis.title.x = element_text(
      size = 11
    ),
    axis.text.x = element_text(
      size = 9
    ),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "bold",
      size = 11
    ),
    legend.position = "none",
    panel.background = element_rect(
      fill = "white",
      color = NA
    ),
    plot.background = element_rect(
      fill = "white",
      color = NA
    ),
    panel.spacing = unit(
      1,
      "lines"
    ),
    plot.margin = margin(
      8,
      12,
      8,
      8
    )
  )


# ------------------------------------------------------------
# 15. Panel C: candidate lookup
# ------------------------------------------------------------

lookup_df <- candidate_positions[
  order(
    candidate_positions$table_no
  ),
  c(
    "table_no",
    "table_no_fmt",
    "gene_id",
    "seqid"
  )
]

lookup_df$entry <- paste0(
  lookup_df$table_no_fmt,
  "   ",
  lookup_df$gene_id,
  "   ",
  lookup_df$seqid
)

n_total <- nrow(
  lookup_df
)

n_col1 <- ceiling(
  n_total / 3
)

n_col2 <- ceiling(
  (
    n_total -
      n_col1
  ) / 2
)

lookup_col1 <- lookup_df[
  1:n_col1,
  ,
  drop = FALSE
]

lookup_col2 <- lookup_df[
  (n_col1 + 1):
    (n_col1 + n_col2),
  ,
  drop = FALSE
]

lookup_col3 <- lookup_df[
  (n_col1 + n_col2 + 1):
    n_total,
  ,
  drop = FALSE
]

lookup_col1$x <- 1
lookup_col2$x <- 2
lookup_col3$x <- 3

lookup_col1$y <- rev(
  seq_len(
    nrow(lookup_col1)
  )
)

lookup_col2$y <- rev(
  seq_len(
    nrow(lookup_col2)
  )
)

lookup_col3$y <- rev(
  seq_len(
    nrow(lookup_col3)
  )
)

lookup_plot_df <- rbind(
  lookup_col1,
  lookup_col2,
  lookup_col3
)

max_y_lookup <- max(
  lookup_plot_df$y
)


# ============================================================
# PANEL C
# ============================================================

p_lookup <- ggplot(
  lookup_plot_df,
  aes(
    x = x,
    y = y,
    label = entry
  )
) +

  geom_text(
    hjust = 0,
    size = 3.0
  ) +

  annotate(
    "text",
    x = 1,
    y = max_y_lookup + 1.8,
    label = "No.   Gene ID   Contig",
    hjust = 0,
    fontface = "bold",
    size = 3.3
  ) +

  annotate(
    "text",
    x = 2,
    y = max_y_lookup + 1.8,
    label = "No.   Gene ID   Contig",
    hjust = 0,
    fontface = "bold",
    size = 3.3
  ) +

  annotate(
    "text",
    x = 3,
    y = max_y_lookup + 1.8,
    label = "No.   Gene ID   Contig",
    hjust = 0,
    fontface = "bold",
    size = 3.3
  ) +

  xlim(
    0.9,
    3.9
  ) +

  ylim(
    0.5,
    max_y_lookup + 2.5
  ) +

  theme_void() +

  theme(
    plot.title = element_text(
      face = "bold",
      size = 13,
      hjust = 0
    ),
    panel.background = element_rect(
      fill = "white",
      color = NA
    ),
    plot.background = element_rect(
      fill = "white",
      color = NA
    ),
    plot.margin = margin(
      5,
      5,
      5,
      5
    )
  ) +

  labs(
    title =
      "C  Candidate gene lookup"
  )


# ------------------------------------------------------------
# 16. Combine panels
# ------------------------------------------------------------

draw_combined_figure <- function() {

  grid.newpage()

  pushViewport(
    viewport(
      layout = grid.layout(
        nrow = 3,
        ncol = 1,
        heights = unit(
          c(
            2.7,
            1.15,
            1.35
          ),
          "null"
        )
      )
    )
  )

  print(
    p_overview,
    vp = viewport(
      layout.pos.row = 1,
      layout.pos.col = 1
    )
  )

  print(
    p_zoom,
    vp = viewport(
      layout.pos.row = 2,
      layout.pos.col = 1
    )
  )

  print(
    p_lookup,
    vp = viewport(
      layout.pos.row = 3,
      layout.pos.col = 1
    )
  )
}


# ------------------------------------------------------------
# 17. Export SVG
# ------------------------------------------------------------

svg_file <- file.path(
  figdir,
  "Supplementary_Figure_genomic_distribution_aa_genes_FINAL.svg"
)

if (
  requireNamespace(
    "svglite",
    quietly = TRUE
  )
) {

  svglite::svglite(
    file = svg_file,
    width = 14,
    height = 15.5
  )

} else {

  grDevices::svg(
    filename = svg_file,
    width = 14,
    height = 15.5,
    onefile = FALSE
  )
}

draw_combined_figure()

dev.off()


# ------------------------------------------------------------
# 18. Export PNG
# ------------------------------------------------------------

png_file <- file.path(
  figdir,
  "Supplementary_Figure_genomic_distribution_aa_genes_FINAL.png"
)

png(
  filename = png_file,
  width = 14,
  height = 15.5,
  units = "in",
  res = 300,
  bg = "white"
)

draw_combined_figure()

dev.off()


# ------------------------------------------------------------
# 19. Console summary
# ------------------------------------------------------------

cat(
  "\nSupplementary figure created.\n",
  "SVG: ",
  svg_file,
  "\nPNG: ",
  png_file,
  "\n",
  sep = ""
)
