#!/usr/bin/env Rscript

# ============================================================
# 14_ctg005830_expression_check.R
#
# Examine expression and genotype-associated differences for all
# annotated genes on ctg005830.
#
# Inputs generated by earlier workflow steps:
#   <project>/deseq2/results/tximport_gene_level.rds
#   <project>/deseq2/results/dds_t0_model.rds
#   <project>/deseq2/results/dds_t24_model.rds
#   <project>/deseq2/results/genotype_background_analysis/gff_genes.rds
#   <project>/deseq2/results/genotype_background_analysis/
#       strict_aa_signature_57_genes_annotated_positions.rds
#
# By default, <project> is /vol/data/digitalis_rnaseq.
# Set DIGITALIS_RNASEQ_DIR to use another project directory.
# ============================================================

suppressPackageStartupMessages({
  library(DESeq2)
})

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

project_dir <- Sys.getenv(
  "DIGITALIS_RNASEQ_DIR",
  unset = "/vol/data/digitalis_rnaseq"
)

results_dir <- file.path(
  project_dir,
  "deseq2",
  "results"
)

outdir <- file.path(
  results_dir,
  "genotype_background_analysis"
)

dir.create(
  outdir,
  recursive = TRUE,
  showWarnings = FALSE
)

txi_file <- file.path(
  results_dir,
  "tximport_gene_level.rds"
)

dds_t0_file <- file.path(
  results_dir,
  "dds_t0_model.rds"
)

dds_t24_file <- file.path(
  results_dir,
  "dds_t24_model.rds"
)

gff_genes_file <- file.path(
  outdir,
  "gff_genes.rds"
)

persistent57_file <- file.path(
  outdir,
  "strict_aa_signature_57_genes_annotated_positions.rds"
)

for (f in c(
  txi_file,
  dds_t0_file,
  dds_t24_file,
  gff_genes_file,
  persistent57_file
)) {
  if (!file.exists(f)) {
    stop("Missing input file: ", f)
  }
}

# ------------------------------------------------------------
# 2. Load data
# ------------------------------------------------------------

txi <- readRDS(txi_file)
dds_t0 <- readRDS(dds_t0_file)
dds_t24 <- readRDS(dds_t24_file)
gff_genes <- readRDS(gff_genes_file)
persistent57 <- readRDS(persistent57_file)

if (is.null(txi$counts) || is.null(txi$abundance)) {
  stop("The tximport object must contain gene-level counts and TPM values.")
}

required_gff_cols <- c(
  "gene_id",
  "seqid",
  "start",
  "end"
)

if (!all(required_gff_cols %in% names(gff_genes))) {
  stop(
    "gff_genes.rds is missing required columns: ",
    paste(
      setdiff(required_gff_cols, names(gff_genes)),
      collapse = ", "
    )
  )
}

if (!all(
  c(
    "gene_id",
    "seqid",
    "shrink_rank"
  ) %in% names(persistent57)
)) {
  stop(
    "The persistent-gene table must contain gene_id, seqid and shrink_rank."
  )
}

# ------------------------------------------------------------
# 3. Extract all annotated genes on ctg005830
# ------------------------------------------------------------

target_contig <- "ctg005830"

ctg <- gff_genes[
  gff_genes$seqid == target_contig,
  required_gff_cols
]

ctg$start <- as.numeric(as.character(ctg$start))
ctg$end <- as.numeric(as.character(ctg$end))

ctg <- ctg[
  order(ctg$start),
]

rownames(ctg) <- NULL

ctg$midpoint <- (
  ctg$start +
    ctg$end
) / 2

ctg$position_Mb <- ctg$midpoint / 1e6

# ------------------------------------------------------------
# 4. Expression status
#
# Standard filter used throughout the RNA-seq workflow:
# >=10 estimated counts in >=3 samples.
# ------------------------------------------------------------

counts_matrix <- txi$counts
tpm_matrix <- txi$abundance

count_idx <- match(
  ctg$gene_id,
  rownames(counts_matrix)
)

tpm_idx <- match(
  ctg$gene_id,
  rownames(tpm_matrix)
)

ctg$present_in_RNAseq <- !is.na(count_idx)
ctg$total_counts <- NA_real_
ctg$n_samples_counts_ge10 <- NA_integer_
ctg$mean_TPM <- NA_real_
ctg$max_TPM <- NA_real_

ok_counts <- !is.na(count_idx)

ctg$total_counts[ok_counts] <- rowSums(
  counts_matrix[
    count_idx[ok_counts],
    ,
    drop = FALSE
  ]
)

ctg$n_samples_counts_ge10[ok_counts] <- rowSums(
  counts_matrix[
    count_idx[ok_counts],
    ,
    drop = FALSE
  ] >= 10
)

ok_tpm <- !is.na(tpm_idx)

ctg$mean_TPM[ok_tpm] <- rowMeans(
  tpm_matrix[
    tpm_idx[ok_tpm],
    ,
    drop = FALSE
  ]
)

ctg$max_TPM[ok_tpm] <- apply(
  tpm_matrix[
    tpm_idx[ok_tpm],
    ,
    drop = FALSE
  ],
  1,
  max
)

ctg$passes_expression_filter <-
  !is.na(ctg$n_samples_counts_ge10) &
  ctg$n_samples_counts_ge10 >= 3

# ------------------------------------------------------------
# 5. Genotype contrasts at t0 and t24
# ------------------------------------------------------------

res_t0_aa_vs_AA <- results(
  dds_t0,
  contrast = c("genotype", "aa", "AA"),
  alpha = 0.05
)

res_t0_aa_vs_Aa <- results(
  dds_t0,
  contrast = c("genotype", "aa", "Aa"),
  alpha = 0.05
)

res_t24_aa_vs_AA <- results(
  dds_t24,
  contrast = c("genotype", "aa", "AA"),
  alpha = 0.05
)

res_t24_aa_vs_Aa <- results(
  dds_t24,
  contrast = c("genotype", "aa", "Aa"),
  alpha = 0.05
)

res_t0_Aa_vs_AA <- results(
  dds_t0,
  contrast = c("genotype", "Aa", "AA"),
  alpha = 0.05
)

res_t24_Aa_vs_AA <- results(
  dds_t24,
  contrast = c("genotype", "Aa", "AA"),
  alpha = 0.05
)

extract_result <- function(res, genes) {
  idx <- match(
    genes,
    rownames(res)
  )

  data.frame(
    log2FC = res$log2FoldChange[idx],
    padj = res$padj[idx],
    stringsAsFactors = FALSE
  )
}

r1 <- extract_result(
  res_t0_aa_vs_AA,
  ctg$gene_id
)

r2 <- extract_result(
  res_t0_aa_vs_Aa,
  ctg$gene_id
)

r3 <- extract_result(
  res_t24_aa_vs_AA,
  ctg$gene_id
)

r4 <- extract_result(
  res_t24_aa_vs_Aa,
  ctg$gene_id
)

r5 <- extract_result(
  res_t0_Aa_vs_AA,
  ctg$gene_id
)

r6 <- extract_result(
  res_t24_Aa_vs_AA,
  ctg$gene_id
)

ctg$LFC_aa_vs_AA_t0 <- r1$log2FC
ctg$padj_aa_vs_AA_t0 <- r1$padj

ctg$LFC_aa_vs_Aa_t0 <- r2$log2FC
ctg$padj_aa_vs_Aa_t0 <- r2$padj

ctg$LFC_aa_vs_AA_t24 <- r3$log2FC
ctg$padj_aa_vs_AA_t24 <- r3$padj

ctg$LFC_aa_vs_Aa_t24 <- r4$log2FC
ctg$padj_aa_vs_Aa_t24 <- r4$padj

ctg$LFC_Aa_vs_AA_t0 <- r5$log2FC
ctg$padj_Aa_vs_AA_t0 <- r5$padj

ctg$LFC_Aa_vs_AA_t24 <- r6$log2FC
ctg$padj_Aa_vs_AA_t24 <- r6$padj

# ------------------------------------------------------------
# 6. Summarize aa-associated genotype differences
# ------------------------------------------------------------

is_sig <- function(x) {
  !is.na(x) &
    x < 0.05
}

sig_matrix <- cbind(
  is_sig(ctg$padj_aa_vs_AA_t0),
  is_sig(ctg$padj_aa_vs_Aa_t0),
  is_sig(ctg$padj_aa_vs_AA_t24),
  is_sig(ctg$padj_aa_vs_Aa_t24)
)

colnames(sig_matrix) <- c(
  "aa_vs_AA_t0",
  "aa_vs_Aa_t0",
  "aa_vs_AA_t24",
  "aa_vs_Aa_t24"
)

ctg$n_significant_aa_contrasts <- rowSums(
  sig_matrix
)

lfc_matrix <- cbind(
  ctg$LFC_aa_vs_AA_t0,
  ctg$LFC_aa_vs_Aa_t0,
  ctg$LFC_aa_vs_AA_t24,
  ctg$LFC_aa_vs_Aa_t24
)

ctg$same_direction_all4 <- apply(
  lfc_matrix,
  1,
  function(x) {
    if (any(is.na(x))) {
      return(FALSE)
    }

    all(x > 0) ||
      all(x < 0)
  }
)

ctg$significant_AA_vs_Aa <-
  is_sig(ctg$padj_Aa_vs_AA_t0) |
  is_sig(ctg$padj_Aa_vs_AA_t24)

# ------------------------------------------------------------
# 7. Add final 57-set membership and shrinkage rank
# ------------------------------------------------------------

persistent_ctg <- persistent57[
  persistent57$seqid == target_contig,
  c(
    "gene_id",
    "shrink_rank"
  )
]

rank_idx <- match(
  ctg$gene_id,
  persistent_ctg$gene_id
)

ctg$shrink_rank <- as.integer(
  persistent_ctg$shrink_rank[
    rank_idx
  ]
)

ctg$in_final_57 <- !is.na(
  ctg$shrink_rank
)

# Reconstruct the strict criteria as a consistency check.
ctg$matches_strict_57_criteria <-
  ctg$n_significant_aa_contrasts == 4 &
  ctg$same_direction_all4 &
  !ctg$significant_AA_vs_Aa

if (!identical(
  sort(
    ctg$gene_id[
      ctg$matches_strict_57_criteria
    ]
  ),
  sort(
    ctg$gene_id[
      ctg$in_final_57
    ]
  )
)) {
  warning(
    paste0(
      "Strict criteria reconstructed on ctg005830 do not exactly match ",
      "the stored final 57-gene set."
    )
  )
}

# ------------------------------------------------------------
# 8. Classification used for the ctg005830 figure
# ------------------------------------------------------------

ctg$category <- "Not highlighted"

ctg$category[
  ctg$passes_expression_filter &
  ctg$n_significant_aa_contrasts >= 1
] <- "Other partial aa-associated signal"

ctg$category[
  ctg$passes_expression_filter &
  !ctg$in_final_57 &
  ctg$n_significant_aa_contrasts %in% c(2L, 3L) &
  ctg$same_direction_all4
] <- "Partial persistent pattern"

ctg$category[
  ctg$in_final_57
] <- "Final persistent 57-set"

ctg$category <- factor(
  ctg$category,
  levels = c(
    "Final persistent 57-set",
    "Partial persistent pattern",
    "Other partial aa-associated signal",
    "Not highlighted"
  )
)

# ------------------------------------------------------------
# 9. Summary tables
# ------------------------------------------------------------

expressed <- ctg[
  ctg$passes_expression_filter,
]

highlighted <- ctg[
  ctg$category != "Not highlighted",
]

summary_table <- data.frame(
  metric = c(
    "annotated_genes",
    "genes_present_in_RNAseq",
    "genes_passing_expression_filter",
    "expressed_genes_sig_in_at_least_1_of_4_aa_contrasts",
    "expressed_genes_sig_in_at_least_2_of_4_aa_contrasts",
    "expressed_genes_sig_in_at_least_3_of_4_aa_contrasts",
    "expressed_genes_sig_in_all_4_aa_contrasts",
    "genes_from_final_57_set_on_ctg005830"
  ),
  value = c(
    nrow(ctg),
    sum(ctg$present_in_RNAseq),
    nrow(expressed),
    sum(expressed$n_significant_aa_contrasts >= 1),
    sum(expressed$n_significant_aa_contrasts >= 2),
    sum(expressed$n_significant_aa_contrasts >= 3),
    sum(expressed$n_significant_aa_contrasts == 4),
    sum(expressed$in_final_57)
  ),
  stringsAsFactors = FALSE
)

# ------------------------------------------------------------
# 10. Export
# ------------------------------------------------------------

saveRDS(
  ctg,
  file.path(
    outdir,
    "ctg005830_expression_genotype_check.rds"
  )
)

write.csv(
  ctg,
  file.path(
    outdir,
    "ctg005830_expression_genotype_check.csv"
  ),
  row.names = FALSE
)

write.csv(
  highlighted,
  file.path(
    outdir,
    "ctg005830_highlighted_genes.csv"
  ),
  row.names = FALSE
)

write.csv(
  summary_table,
  file.path(
    outdir,
    "ctg005830_analysis_summary.csv"
  ),
  row.names = FALSE
)

# ------------------------------------------------------------
# 11. Console summary
# ------------------------------------------------------------

cat(
  "\nctg005830 expression/genotype check completed.\n\n"
)

print(
  summary_table,
  row.names = FALSE
)

cat(
  "\nHighlighted genes:\n"
)

print(
  highlighted[
    ,
    c(
      "gene_id",
      "start",
      "shrink_rank",
      "n_significant_aa_contrasts",
      "same_direction_all4",
      "category"
    )
  ],
  row.names = FALSE
)
