#!/usr/bin/env Rscript

# ============================================================
# 15_ctg005830_supplementary_figure.R
#
# Create the supplementary figure for ctg005830 using the
# analysis output generated by 14_ctg005830_expression_check.R.
#
# Figure:
#   A) whole-contig overview
#   B) zoom into the first 0.5 Mb
#   C) lookup table for highlighted genes
#
# By default, <project> is /vol/data/digitalis_rnaseq.
# Set DIGITALIS_RNASEQ_DIR to use another project directory.
# ============================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(grid)
})

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

project_dir <- Sys.getenv(
  "DIGITALIS_RNASEQ_DIR",
  unset = "/vol/data/digitalis_rnaseq"
)

results_dir <- file.path(
  project_dir,
  "deseq2",
  "results"
)

outdir <- file.path(
  results_dir,
  "genotype_background_analysis"
)

figdir <- file.path(
  outdir,
  "figures"
)

dir.create(
  figdir,
  recursive = TRUE,
  showWarnings = FALSE
)

analysis_file <- file.path(
  outdir,
  "ctg005830_expression_genotype_check.rds"
)

if (!file.exists(analysis_file)) {
  stop(
    "Missing input file: ",
    analysis_file,
    "\nRun 14_ctg005830_expression_check.R first."
  )
}

# ------------------------------------------------------------
# 2. Load ctg005830 analysis
# ------------------------------------------------------------

ctg <- readRDS(
  analysis_file
)

required_cols <- c(
  "gene_id",
  "start",
  "end",
  "position_Mb",
  "passes_expression_filter",
  "n_significant_aa_contrasts",
  "same_direction_all4",
  "shrink_rank",
  "in_final_57",
  "category"
)

if (!all(required_cols %in% names(ctg))) {
  stop(
    "ctg005830 analysis file is missing required columns: ",
    paste(
      setdiff(required_cols, names(ctg)),
      collapse = ", "
    )
  )
}

ctg$category <- factor(
  as.character(ctg$category),
  levels = c(
    "Final persistent 57-set",
    "Partial persistent pattern",
    "Other partial aa-associated signal",
    "Not highlighted"
  )
)

contig_end_Mb <- max(
  ctg$end,
  na.rm = TRUE
) / 1e6

zoom_start_Mb <- 0
zoom_end_Mb <- 0.5

highlighted <- ctg[
  ctg$category != "Not highlighted",
]

# ------------------------------------------------------------
# 3. Colors and shapes
# ------------------------------------------------------------

col_final <- "#21718C"
col_partial_persistent <- "#7A4DA3"
col_other_partial <- "#D88929"
col_expression <- "grey45"
col_annotation <- "grey82"
zoom_fill <- "#EAF4F7"

category_colors <- c(
  "Final persistent 57-set" =
    col_final,
  "Partial persistent pattern" =
    col_partial_persistent,
  "Other partial aa-associated signal" =
    col_other_partial
)

category_shapes <- c(
  "Final persistent 57-set" = 17,
  "Partial persistent pattern" = 16,
  "Other partial aa-associated signal" = 1
)

# ------------------------------------------------------------
# 4. Panel A: whole-contig overview
# ------------------------------------------------------------

pA <- ggplot() +

  annotate(
    "rect",
    xmin = zoom_start_Mb,
    xmax = zoom_end_Mb,
    ymin = 0.55,
    ymax = 4.45,
    fill = zoom_fill,
    color = NA
  ) +

  geom_segment(
    aes(
      x = 0,
      xend = contig_end_Mb,
      y = 1,
      yend = 1
    ),
    color = "grey90",
    linewidth = 0.35
  ) +

  geom_segment(
    aes(
      x = 0,
      xend = contig_end_Mb,
      y = 2,
      yend = 2
    ),
    color = "grey90",
    linewidth = 0.35
  ) +

  geom_segment(
    aes(
      x = 0,
      xend = contig_end_Mb,
      y = 3,
      yend = 3
    ),
    color = "grey90",
    linewidth = 0.35
  ) +

  geom_segment(
    aes(
      x = 0,
      xend = contig_end_Mb,
      y = 4,
      yend = 4
    ),
    color = "grey90",
    linewidth = 0.35
  ) +

  geom_segment(
    data = ctg,
    aes(
      x = position_Mb,
      xend = position_Mb,
      y = 0.86,
      yend = 1.14
    ),
    color = col_annotation,
    linewidth = 0.45
  ) +

  geom_segment(
    data = ctg[
      ctg$passes_expression_filter,
    ],
    aes(
      x = position_Mb,
      xend = position_Mb,
      y = 1.86,
      yend = 2.14
    ),
    color = col_expression,
    linewidth = 0.50
  ) +

  geom_point(
    data = highlighted,
    aes(
      x = position_Mb,
      y = 3,
      color = category,
      shape = category
    ),
    size = 2.9
  ) +

  geom_point(
    data = ctg[
      ctg$in_final_57,
    ],
    aes(
      x = position_Mb,
      y = 4
    ),
    color = col_final,
    shape = 17,
    size = 3.25
  ) +

  scale_color_manual(
    values = category_colors,
    drop = TRUE
  ) +

  scale_shape_manual(
    values = category_shapes,
    drop = TRUE
  ) +

  scale_y_continuous(
    breaks = c(
      1,
      2,
      3,
      4
    ),
    labels = c(
      "All annotated genes",
      "Pass expression filter",
      "\u22651 significant aa contrast",
      "Final persistent 57-set"
    ),
    limits = c(
      0.5,
      4.5
    )
  ) +

  scale_x_continuous(
    limits = c(
      0,
      contig_end_Mb
    ),
    expand = expansion(
      mult = c(
        0,
        0.01
      )
    )
  ) +

  labs(
    title =
      "A  Genotype-associated expression differences across ctg005830",
    x =
      "Genomic position on ctg005830 (Mb)",
    y = NULL
  ) +

  guides(
    color = "none",
    shape = "none"
  ) +

  theme_classic(
    base_size = 11
  ) +

  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(
      size = 9.5
    ),
    plot.title = element_text(
      face = "bold",
      size = 12,
      hjust = 0
    ),
    plot.margin = margin(
      8,
      18,
      5,
      12
    )
  )

# ------------------------------------------------------------
# 5. Panel B: local group in the first 0.5 Mb
# ------------------------------------------------------------

zoom <- ctg[
  ctg$position_Mb >= zoom_start_Mb &
  ctg$position_Mb <= zoom_end_Mb,
]

zoom_highlighted <- zoom[
  zoom$category != "Not highlighted",
]

zoom_highlighted <- zoom_highlighted[
  order(
    zoom_highlighted$position_Mb
  ),
]

# Fixed label positions reproduce the final layout used in the thesis.
label_layout <- data.frame(
  gene_id = c(
    "DP130691",
    "DP130692",
    "DP130693",
    "DP130694",
    "DP130695",
    "DP130696",
    "DP130698",
    "DP130700",
    "DP130704"
  ),
  label_x = c(
    0.085,
    0.105,
    0.128,
    0.155,
    0.178,
    0.205,
    0.260,
    0.305,
    0.420
  ),
  label_y = c(
    3.62,
    3.95,
    4.28,
    3.62,
    3.95,
    4.28,
    3.72,
    4.08,
    4.02
  ),
  stringsAsFactors = FALSE
)

layout_idx <- match(
  zoom_highlighted$gene_id,
  label_layout$gene_id
)

if (anyNA(layout_idx)) {
  stop(
    "Panel B label layout is missing one or more highlighted genes."
  )
}

zoom_highlighted$label_x <-
  label_layout$label_x[
    layout_idx
  ]

zoom_highlighted$label_y <-
  label_layout$label_y[
    layout_idx
  ]

pB <- ggplot() +

  geom_segment(
    data = zoom,
    aes(
      x = position_Mb,
      xend = position_Mb,
      y = 0.86,
      yend = 1.14
    ),
    color = col_annotation,
    linewidth = 0.55
  ) +

  geom_segment(
    data = zoom[
      zoom$passes_expression_filter,
    ],
    aes(
      x = position_Mb,
      xend = position_Mb,
      y = 1.86,
      yend = 2.14
    ),
    color = col_expression,
    linewidth = 0.65
  ) +

  geom_point(
    data = zoom_highlighted,
    aes(
      x = position_Mb,
      y = 2.90,
      color = category,
      shape = category
    ),
    size = 3.4
  ) +

  geom_segment(
    data = zoom_highlighted,
    aes(
      x = position_Mb,
      y = 3.03,
      xend = label_x,
      yend = label_y - 0.10
    ),
    color = "grey58",
    linewidth = 0.35
  ) +

  geom_text(
    data = zoom_highlighted,
    aes(
      x = label_x,
      y = label_y,
      label = gene_id
    ),
    angle = 34,
    hjust = 0,
    vjust = 0,
    size = 3.05
  ) +

  scale_color_manual(
    values = category_colors,
    drop = TRUE
  ) +

  scale_shape_manual(
    values = category_shapes,
    drop = TRUE
  ) +

  scale_y_continuous(
    breaks = c(
      1,
      2,
      2.90
    ),
    labels = c(
      "All annotated genes",
      "Pass expression filter",
      "aa-associated expression difference"
    ),
    limits = c(
      0.55,
      4.65
    )
  ) +

  scale_x_continuous(
    limits = c(
      zoom_start_Mb,
      zoom_end_Mb
    ),
    expand = expansion(
      mult = c(
        0.015,
        0.04
      )
    )
  ) +

  labs(
    title =
      "B  Zoom on the local group on ctg005830",
    x =
      "Genomic position on ctg005830 (Mb)",
    y = NULL
  ) +

  guides(
    color = "none",
    shape = "none"
  ) +

  theme_classic(
    base_size = 11
  ) +

  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(
      size = 9.5
    ),
    plot.title = element_text(
      face = "bold",
      size = 12,
      hjust = 0
    ),
    plot.margin = margin(
      8,
      18,
      4,
      12
    )
  )

# ------------------------------------------------------------
# 6. Complete two-row figure legend
# ------------------------------------------------------------

pLegend <- ggplot() +

  annotate(
    "point",
    x = 0.055,
    y = 1.65,
    shape = 17,
    size = 3.4,
    color = col_final
  ) +

  annotate(
    "text",
    x = 0.085,
    y = 1.65,
    label = "Final persistent 57-set",
    hjust = 0,
    vjust = 0.5,
    size = 3.1
  ) +

  annotate(
    "point",
    x = 0.355,
    y = 1.65,
    shape = 16,
    size = 3.2,
    color = col_partial_persistent
  ) +

  annotate(
    "text",
    x = 0.385,
    y = 1.65,
    label = "Partial persistent pattern",
    hjust = 0,
    vjust = 0.5,
    size = 3.1
  ) +

  annotate(
    "point",
    x = 0.665,
    y = 1.65,
    shape = 1,
    size = 3.4,
    stroke = 1.0,
    color = col_other_partial
  ) +

  annotate(
    "text",
    x = 0.695,
    y = 1.65,
    label = "Other partial aa-associated signal",
    hjust = 0,
    vjust = 0.5,
    size = 3.1
  ) +

  annotate(
    "segment",
    x = 0.315,
    xend = 0.315,
    y = 0.74,
    yend = 1.06,
    linewidth = 0.9,
    color = col_expression
  ) +

  annotate(
    "text",
    x = 0.345,
    y = 0.90,
    label = "Pass expression filter",
    hjust = 0,
    vjust = 0.5,
    size = 3.1
  ) +

  annotate(
    "segment",
    x = 0.610,
    xend = 0.610,
    y = 0.74,
    yend = 1.06,
    linewidth = 0.9,
    color = col_annotation
  ) +

  annotate(
    "text",
    x = 0.640,
    y = 0.90,
    label = "All annotated genes",
    hjust = 0,
    vjust = 0.5,
    size = 3.1
  ) +

  coord_cartesian(
    xlim = c(
      0,
      1.06
    ),
    ylim = c(
      0.45,
      2.00
    ),
    clip = "off"
  ) +

  theme_void() +

  theme(
    plot.margin = margin(
      0,
      22,
      2,
      12
    )
  )

# ------------------------------------------------------------
# 7. Panel C: highlighted-gene lookup
# ------------------------------------------------------------

table_df <- highlighted[
  order(
    highlighted$position_Mb
  ),
]

table_df$Rank <- ifelse(
  is.na(
    table_df$shrink_rank
  ),
  "-",
  sprintf(
    "%02d",
    table_df$shrink_rank
  )
)

table_df$Position <- sprintf(
  "%.3f",
  table_df$position_Mb
)

table_df$SigContrasts <- paste0(
  table_df$n_significant_aa_contrasts,
  "/4"
)

table_df$ClassShort <- ifelse(
  as.character(
    table_df$category
  ) == "Final persistent 57-set",
  "Final 57-set",
  ifelse(
    as.character(
      table_df$category
    ) == "Partial persistent pattern",
    "Partial persistent",
    "Partial signal"
  )
)

table_df$table_y <- rev(
  seq_len(
    nrow(table_df)
  )
)

header_y <- max(
  table_df$table_y
) + 1.25

x_symbol <- 0.025
x_rank <- 0.115
x_gene <- 0.275
x_pos <- 0.495
x_sig <- 0.685
x_class <- 0.845

pC <- ggplot() +

  geom_rect(
    data = table_df,
    aes(
      xmin = 0,
      xmax = 1.06,
      ymin = table_y - 0.42,
      ymax = table_y + 0.42,
      fill = category
    ),
    alpha = 0.18,
    color = NA
  ) +

  geom_point(
    data = table_df,
    aes(
      x = x_symbol,
      y = table_y,
      color = category,
      shape = category
    ),
    size = 3.0
  ) +

  geom_text(
    data = table_df,
    aes(
      x = x_rank,
      y = table_y,
      label = Rank
    ),
    hjust = 0.5,
    size = 3.15
  ) +

  geom_text(
    data = table_df,
    aes(
      x = x_gene,
      y = table_y,
      label = gene_id
    ),
    hjust = 0.5,
    size = 3.15
  ) +

  geom_text(
    data = table_df,
    aes(
      x = x_pos,
      y = table_y,
      label = Position
    ),
    hjust = 0.5,
    size = 3.15
  ) +

  geom_text(
    data = table_df,
    aes(
      x = x_sig,
      y = table_y,
      label = SigContrasts
    ),
    hjust = 0.5,
    size = 3.15
  ) +

  geom_text(
    data = table_df,
    aes(
      x = x_class,
      y = table_y,
      label = ClassShort
    ),
    hjust = 0,
    size = 3.05
  ) +

  annotate(
    "text",
    x = x_rank,
    y = header_y,
    label = "Rank",
    hjust = 0.5,
    fontface = "bold",
    size = 3.35
  ) +

  annotate(
    "text",
    x = x_gene,
    y = header_y,
    label = "Gene ID",
    hjust = 0.5,
    fontface = "bold",
    size = 3.35
  ) +

  annotate(
    "text",
    x = x_pos,
    y = header_y,
    label = "Position (Mb)",
    hjust = 0.5,
    fontface = "bold",
    size = 3.35
  ) +

  annotate(
    "text",
    x = x_sig,
    y = header_y,
    label = "Sig. aa contrasts",
    hjust = 0.5,
    fontface = "bold",
    size = 3.25
  ) +

  annotate(
    "text",
    x = x_class,
    y = header_y,
    label = "Classification",
    hjust = 0,
    fontface = "bold",
    size = 3.35
  ) +

  scale_fill_manual(
    values = category_colors,
    guide = "none"
  ) +

  scale_color_manual(
    values = category_colors,
    guide = "none"
  ) +

  scale_shape_manual(
    values = category_shapes,
    guide = "none"
  ) +

  coord_cartesian(
    xlim = c(
      0,
      1.06
    ),
    ylim = c(
      0.25,
      header_y + 0.75
    ),
    clip = "off"
  ) +

  labs(
    title =
      "C  Highlighted genes on ctg005830"
  ) +

  theme_void(
    base_size = 11
  ) +

  theme(
    plot.title = element_text(
      face = "bold",
      size = 12,
      hjust = 0
    ),
    plot.margin = margin(
      10,
      22,
      8,
      12
    )
  )

# ------------------------------------------------------------
# 8. Combine figure
# ------------------------------------------------------------

draw_final_figure <- function() {

  grid.newpage()

  pushViewport(
    viewport(
      layout = grid.layout(
        nrow = 4,
        ncol = 1,
        heights = unit(
          c(
            1.00,
            1.30,
            0.34,
            1.34
          ),
          "null"
        )
      )
    )
  )

  print(
    pA,
    vp = viewport(
      layout.pos.row = 1,
      layout.pos.col = 1
    )
  )

  print(
    pB,
    vp = viewport(
      layout.pos.row = 2,
      layout.pos.col = 1
    )
  )

  print(
    pLegend,
    vp = viewport(
      layout.pos.row = 3,
      layout.pos.col = 1
    )
  )

  print(
    pC,
    vp = viewport(
      layout.pos.row = 4,
      layout.pos.col = 1
    )
  )
}

# ------------------------------------------------------------
# 9. Export figure and lookup table
# ------------------------------------------------------------

svg_file <- file.path(
  figdir,
  "Supplementary_Figure_ctg005830.svg"
)

svg(
  filename = svg_file,
  width = 11.8,
  height = 14.0
)

draw_final_figure()

dev.off()

png_file <- file.path(
  figdir,
  "Supplementary_Figure_ctg005830.png"
)

png(
  filename = png_file,
  width = 3540,
  height = 4200,
  res = 300
)

draw_final_figure()

dev.off()

lookup_export <- data.frame(
  Rank = table_df$Rank,
  Gene_ID = table_df$gene_id,
  Position_Mb = table_df$Position,
  Significant_aa_contrasts =
    table_df$SigContrasts,
  Classification =
    table_df$ClassShort,
  stringsAsFactors = FALSE
)

write.csv(
  lookup_export,
  file.path(
    outdir,
    "ctg005830_highlighted_gene_lookup.csv"
  ),
  row.names = FALSE
)

cat(
  "\nSupplementary ctg005830 figure completed.\n"
)

cat(
  "SVG: ",
  svg_file,
  "\n",
  sep = ""
)

cat(
  "PNG: ",
  png_file,
  "\n",
  sep = ""
)
